apiVersion: v1
kind: Service
metadata:
  annotations:
    com.quorum.consensus: istanbul
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: node6
  name: node6
spec:
  ports:
  - name: "22005"
    port: 22005
    targetPort: 8545
  selector:
    io.kompose.service: node6
status:
  loadBalancer: {}
