apiVersion: v1
kind: Service
metadata:
  annotations:
    com.quorum.consensus: istanbul
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: node2
  name: node2
spec:
  ports:
  - name: "22001"
    port: 22001
    targetPort: 8545
  selector:
    io.kompose.service: node2
status:
  loadBalancer: {}
