apiVersion: v1
kind: Service
metadata:
  annotations:
    com.quorum.consensus: istanbul
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: node4
  name: node4
spec:
  ports:
  - name: "22003"
    port: 22003
    targetPort: 8545
  selector:
    io.kompose.service: node4
status:
  loadBalancer: {}
