apiVersion: v1
kind: Service
metadata:
  annotations:
    com.quorum.consensus: istanbul
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: node1
  name: node1
spec:
  ports:
  - name: "22000"
    port: 22000
    targetPort: 8545
  selector:
    io.kompose.service: node1
status:
  loadBalancer: {}
