apiVersion: v1
kind: Service
metadata:
  annotations:
    com.quorum.consensus: istanbul
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: node3
  name: node3
spec:
  ports:
  - name: "22002"
    port: 22002
    targetPort: 8545
  selector:
    io.kompose.service: node3
status:
  loadBalancer: {}
