apiVersion: v1
kind: Service
metadata:
  annotations:
    com.quorum.consensus: istanbul
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: node5
  name: node5
spec:
  ports:
  - name: "22004"
    port: 22004
    targetPort: 8545
  selector:
    io.kompose.service: node5
status:
  loadBalancer: {}
