apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: racecourse
  labels:
    app: racecourse
spec:
  rules:
    - host: racecource
      http:
        paths:
          - path: /
            backend:
              serviceName: racecource
              servicePort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: racecourse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: racecourse
  labels:
    app: racecourse
    tier: frontend
spec:
  selector:
    matchLabels:
      app: racecourse
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: racecourse
        tier: frontend
    spec:
      containers:
      - image: 'burnmydread/racecource:latest'
        name: racecourse
        ports:
        - containerPort: 80
      hostname: racecource
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: racecourse
  name: racecourse
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: racecourse
