apiVersion: v1
kind: Service
metadata:
  name: racecourse
  labels:
    app: racecourse
spec:
  ports:
    - port: 80
  selector:
    app: racecourse
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: racecourse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: racecourse
  labels:
    app: racecourse
spec:
  selector:
    matchLabels:
      app: racecourse
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: racecourse
        tier: frontend
    spec:
      containers:
      - image: 'burnmydread/racecource:latest'
        name: racecourse
        env:
        - name: WORDPRESS_DB_HOST
          value: racecourse-mysql
        ports:
        - containerPort: 80
          name: racecourse
