apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: txmanager4
  name: txmanager4
spec:
  ports:
  - name: "9084"
    port: 9084
    targetPort: 9080
  selector:
    io.kompose.service: txmanager4
status:
  loadBalancer: {}
