apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: txmanager5
  name: txmanager5
spec:
  ports:
  - name: "9085"
    port: 9085
    targetPort: 9080
  selector:
    io.kompose.service: txmanager5
status:
  loadBalancer: {}
