apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: txmanager6
  name: txmanager6
spec:
  ports:
  - name: "9086"
    port: 9086
    targetPort: 9080
  selector:
    io.kompose.service: txmanager6
status:
  loadBalancer: {}
