apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: txmanager1
  name: txmanager1
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - |
      DDIR=/qdata/tm
      rm -rf ${DDIR}
      mkdir -p ${DDIR}
      DOCKER_IMAGE="quorumengineering/tessera:0.7.3"
      TX_MANAGER=$(echo ${DOCKER_IMAGE} | sed 's/^.*\/\(.*\):.*$/\1/g')
      echo "TxManager: ${TX_MANAGER}"
      case ${TX_MANAGER}
      in
        tessera)
          cp /examples/keys/tm${NODE_ID}.pub ${DDIR}/tm.pub
          cp /examples/keys/tm${NODE_ID}.key ${DDIR}/tm.key
          #extract the tessera version from the jar
          TESSERA_VERSION=$(unzip -p /tessera/tessera-app.jar META-INF/MANIFEST.MF | grep Tessera-Version | cut -d" " -f2)
          echo "Tessera version (extracted from manifest file): ${TESSERA_VERSION}"
          #we're going to do a lexicographic comparison further down so we need "0.8" to be bigger than "0.8 " - thus adding -suffix
          TESSERA_VERSION="${TESSERA_VERSION}-suffix"

          TESSERA_CONFIG_TYPE=

          #the space in "0.8 " is important in the lexicographic comparision (space is lower value than most printable chars)
          #TODO - this will break when we get to version 0.10 (hopefully we would have moved to 1.x by then)
          if [ "${TESSERA_VERSION}" \> "0.8 " ]; then
              TESSERA_CONFIG_TYPE="-enhanced"
          fi

          echo Config type ${TESSERA_CONFIG_TYPE}

          #generating the two config flavors
          cat <<EOF > ${DDIR}/tessera-config.json
          {
              "useWhiteList": false,
              "jdbc": {
                  "username": "sa",
                  "password": "",
                  "url": "jdbc:h2:./${DDIR}/db;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
                  "autoCreateTables": true
              },
              "server": {
                  "port": 9000,
                  "hostName": "http://$(hostname -i)",
                  "sslConfig": {
                      "tls": "OFF",
                      "generateKeyStoreIfNotExisted": true,
                      "serverKeyStore": "${DDIR}/server-keystore",
                      "serverKeyStorePassword": "quorum",
                      "serverTrustStore": "${DDIR}/server-truststore",
                      "serverTrustStorePassword": "quorum",
                      "serverTrustMode": "TOFU",
                      "knownClientsFile": "${DDIR}/knownClients",
                      "clientKeyStore": "${DDIR}/client-keystore",
                      "clientKeyStorePassword": "quorum",
                      "clientTrustStore": "${DDIR}/client-truststore",
                      "clientTrustStorePassword": "quorum",
                      "clientTrustMode": "TOFU",
                      "knownServersFile": "${DDIR}/knownServers"
                  }
              },
              "peer": [
                  {
                      "url": "http://txmanager1:9000"
                  },
                  {
                      "url": "http://txmanager2:9000"
                  },
                  {
                      "url": "http://txmanager3:9000"
                  },
                  {
                      "url": "http://txmanager4:9000"
                  },
                  {
                      "url": "http://txmanager5:9000"
                  },
                  {
                      "url": "http://txmanager6:9000"
                  },
                  {
                      "url": "http://txmanager7:9000"
                  }
              ],
              "keys": {
                  "passwords": [],
                  "keyData": [
                      {
                          "config": $(cat ${DDIR}/tm.key),
                          "publicKey": "$(cat ${DDIR}/tm.pub)"
                      }
                  ]
              },
              "alwaysSendTo": [],
              "unixSocketFile": "${DDIR}/tm.ipc"
          }
      EOF

          cat <<EOF > ${DDIR}/tessera-config-enhanced.json
          {
            "useWhiteList": false,
            "jdbc": {
              "username": "sa",
              "password": "",
              "url": "jdbc:h2:./${DDIR}/db;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
              "autoCreateTables": true
            },
            "serverConfigs":[
            {
              "app":"ThirdParty",
              "enabled": true,
              "serverSocket":{
                "type":"INET",
                "port": 9080,
                "hostName": "http://$(hostname -i)"
              },
              "communicationType" : "REST"
            },
            {
              "app":"Q2T",
              "enabled": true,
              "serverSocket":{
                "type":"UNIX",
                "path":"${DDIR}/tm.ipc"
              },
              "communicationType" : "UNIX_SOCKET"
            },
            {
              "app":"P2P",
              "enabled": true,
              "serverSocket":{
                "type":"INET",
                "port": 9000,
                "hostName": "http://$(hostname -i)"
              },
              "sslConfig": {
                "tls": "OFF",
                "generateKeyStoreIfNotExisted": true,
                "serverKeyStore": "${DDIR}/server-keystore",
                "serverKeyStorePassword": "quorum",
                "serverTrustStore": "${DDIR}/server-truststore",
                "serverTrustStorePassword": "quorum",
                "serverTrustMode": "TOFU",
                "knownClientsFile": "${DDIR}/knownClients",
                "clientKeyStore": "${DDIR}/client-keystore",
                "clientKeyStorePassword": "quorum",
                "clientTrustStore": "${DDIR}/client-truststore",
                "clientTrustStorePassword": "quorum",
                "clientTrustMode": "TOFU",
                "knownServersFile": "${DDIR}/knownServers"
              },
              "communicationType" : "REST"
            }
            ],
            "peer": [
               {
                   "url": "http://txmanager1:9000"
               },
               {
                   "url": "http://txmanager2:9000"
               },
               {
                   "url": "http://txmanager3:9000"
               },
               {
                   "url": "http://txmanager4:9000"
               },
               {
                   "url": "http://txmanager5:9000"
               },
               {
                   "url": "http://txmanager6:9000"
               },
               {
                   "url": "http://txmanager7:9000"
               }
            ],
            "keys": {
              "passwords": [],
              "keyData": [
                {
                  "config": $(cat ${DDIR}/tm.key),
                  "publicKey": "$(cat ${DDIR}/tm.pub)"
                }
              ]
            },
            "alwaysSendTo": []
          }
      EOF

          java -Xms128M -Xmx128M -jar /tessera/tessera-app.jar -configfile ${DDIR}/tessera-config${TESSERA_CONFIG_TYPE}.json
          ;;
        constellation)
          echo "socket=\"${DDIR}/tm.ipc\"\npublickeys=[\"/examples/keys/tm${NODE_ID}.pub\"]\n" > ${DDIR}/tm.conf
          constellation-node \
            --url=http://$(hostname -i):9000/ \
            --port=9000 \
            --socket=${DDIR}/tm.ipc \
            --othernodes=http://172.16.239.101:9000/,http://172.16.239.102:9000/,http://172.16.239.103:9000/,http://172.16.239.104:9000/,http://172.16.239.105:9000/ \
            --publickeys=/examples/keys/tm${NODE_ID}.pub \
            --privatekeys=/examples/keys/tm${NODE_ID}.key \
            --storage=${DDIR} \
            --verbosity=4
          ;;
        *)
          echo "Invalid Transaction Manager"
          exit 1
          ;;
      esac
    env:
    - name: NODE_ID
      value: "1"
    image: quorumengineering/tessera:0.7.3
    livenessProbe:
      exec:
        command:
        - '[ -S /qdata/tm/tm.ipc ] || exit 1'
      failureThreshold: 20
      periodSeconds: 5
      timeoutSeconds: 5
    name: txmanager1
    ports:
    - containerPort: 9080
    resources: {}
    volumeMounts:
    - mountPath: /qdata
      name: vol1
    - mountPath: /examples
      name: txmanager1-claim1
      readOnly: true
  hostname: txmanager1
  restartPolicy: Never
  volumes:
  - name: vol1
    persistentVolumeClaim:
      claimName: vol1
  - name: txmanager1-claim1
    persistentVolumeClaim:
      claimName: txmanager1-claim1
      readOnly: true
status: {}
