apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: txmanager1
  name: txmanager1
spec:
  ports:
  - name: "9081"
    port: 9081
    targetPort: 9080
  selector:
    io.kompose.service: txmanager1
status:
  loadBalancer: {}
