apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: vol2
  name: vol2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
